### ISSUE TITLE
possible support for friendsofsymfony/elastica-bundle 5.x ?

### ISSUE THREAD

**Issue by tschackmack** [sonata-project/SonataAdminSearchBundle#125]
Hi!
are there plans for an upgrade?
Thanks and regards,
tschackmack

**Comment by core23** [comment]
Feel free to test it our to supply a PR.

**Comment by ibasaw** [comment]
news ?

php  >= 7.2
friendsofsymfony/elastica-bundle >= 5

**Comment by OskarStark** [comment]
Not from the core teams side, but a PR is appreciated 👌🏻
