### ISSUE TITLE
Batch action raise exception

### ISSUE THREAD

**Issue by chervaliery** [sonata-project/SonataAdminSearchBundle#13]
If you use ElasticSearch in your admin class and you select several objects for a batch action or even to delete them, it cause this exception: 

> Error: Call to a member function field() on a non-object in vendor/sonata-project/doctrine-mongodb-admin-bundle/Sonata/DoctrineMongoDBAdminBundle/Model/ModelManager.php line 313

In the Model Manger, the addIdentifiersToQuery function receive here an ElasticaProxyQuery 

``` php
    public function addIdentifiersToQuery($class, ProxyQueryInterface $queryProxy, array $idx)
    {
        $queryBuilder = $queryProxy->getQueryBuilder();
        $queryBuilder->field('_id')->in($idx);
    }
```

But the ElasticaProxyQuery does not have a QueryBuilder.

Would it be possible to add a kind of ''fake'' queryBuilder ?

**Comment by greg0ire** [comment]
> Would it be possible to add a kind of ''fake'' queryBuilder ?

What happens when you try ? I guess you no longer get a 500, but then I supposed the query is not filtered by id anymore…

**Comment by chervaliery** [comment]
I said that, but I have no idea how to do this.
Normally, you create a queryBuilder from an entityManger :
http://doctrine-orm.readthedocs.org/en/latest/reference/query-builder.html#constructing-a-new-querybuilder-object

``` php
$qb = $em->createQueryBuilder();
```

But here we cannot.

**Comment by chervaliery** [comment]
When you select several objects and use a batch action, Sonata create a query like `SELECT * FROM yourentity WHERE id = ‘id1’ OR id = ‘id2’ OR id = ‘id3’…` in ORM
Or like `db.yourcollection.find({‘id’ IN [‘id1’, ‘id2’, ‘id3’…]})` in ODM
Then the query is executed and the result collection is passed to the batch action.

Here, the ProxyQuery passed to the model Manager is an ElasticaProxyQuery and the Model Manager cannot do the `$queryBuilder->andWhere('_id' = $idx);` or the `$queryBuilder->field('_id')->in($idx);`

But as we already have the ids, we no longer need ElasticSearch for this query so the ProxyQuery passed to the model Manager should be the ORM/ODM ProxyQuery, the original one (a bit like for the smartDatagrid).
But I don't know how to pass the original ProxyQuery instead of the Elastica one...
Any idea ?

**Comment by greg0ire** [comment]
I do not have the time to investigate right now, but I guess you could try to do just like for smart datagrid…

**Comment by greg0ire** [comment]
Maybe we should not use elastica at all for batch actions ? That would mean forcing the DatagridBuilder to return the "non-smart" datagrid builder…

**Comment by greg0ire** [comment]
Maybe you could change `ElasticaDatagridBuilder::isSmart` so that when `$values` consists only of ids (and here, we would assume people do not name their field id if it is not a primary key ? Or maybe we would have another way to determine if a field is a primary key ?), it returns false ?

**Comment by sidz** [comment]
any idea how to resolve this issue?

**Comment by greg0ire** [comment]
See my last 3 messages.
