### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by grekpg** [sonata-project/SonataAdminSearchBundle#169]
## Feature Request

Im try to install this nice bundle to Symfony 4 but is not possible 

sonata-project/admin-search-bundle 1.1.0 requires friendsofsymfony/elastica-bundle ^3.1

https://packagist.org/packages/friendsofsymfony/elastica-bundle - v3 not work for current stable Symfony 4. 

Any plan to add compatibility ?

**Comment by core23** [comment]
We as the current maintenance team have no active plans for this bundle. ATM we keep it alive by reviewing PRs and merging them. Please have a look at https://github.com/sonata-project/SonataAdminSearchBundle/issues/160

**Comment by Chrysweel** [comment]
@core23  We want to integrate elasticSearch into sonata, is there any other alternative to this bundle?

**Comment by franmomu** [comment]
Not that I'm aware of, there has been no release, but the `1.x` branch is "compatible" (test passes) with Symfony 4.
