### ISSUE TITLE
Notice: Undefined offset: 1

### ISSUE THREAD

**Issue by magedan** [sonata-project/SonataAdminSearchBundle#24]
When I use "doctrine_orm_model_autocomplete" filter I get following notice:

> Notice: Undefined offset: 1
> in vendor/sonata-project/admin-search-bundle/Builder/ElasticaDatagridBuilder.php at line 137

Here is simple admin config example:

``` php
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add(
                'parent',
                'doctrine_orm_model_autocomplete',
                [
                    'show_filter' => true,
                ],
                null,
                [
                    'property'    => 'name',
                ]
            );
    }
```

and the code which is referenced by the notice above:

``` php
    // first : validate if elastica is asked in the configuration for this action
    $fullCurrentAction = $admin->getRequest()->attributes->get('_controller');
    $currentAction = explode('::', $fullCurrentAction);
    // remove Action from 'listAction'
    $currentAction = substr($currentAction[1], 0, -strlen('Action'));
```

In this case (autocomplete action), $fullCurrentAction equals to "sonata.admin.controller.admin:retrieveAutocompleteItemsAction".

Possibly relates to #22.

**Comment by greg0ire** [comment]
`sonata.admin.controller.admin:retrieveAutocompleteItemsAction` , with only one colon? When does this occur? @Kertudex, any insight?

**Comment by magedan** [comment]
This occurs when I try to use autocomplete input on the datagrid filter form.

The URL requested via AJAX (according to my local Sonata setup):
https://site.loc/app_dev.php/admin/core/get-autocomplete-items?q=cha&_per_page=10&_page=1&admin_code=sonata.admin.synonym&field=parent&_context=filter&_=1452528590860

Response results in 500, so, autocomplete doesn't work.

**Comment by greg0ire** [comment]
I'm not so familiar with the `_controller` notation, but here are what there are more possibilities than what @Kertudex thought, I think. In my project, here is a valid value : `FrameworkBundle:Redirect:redirect` I guess `sonata.admin.controller.admin:retrieveAutocompleteItemsAction` is valid too, and `sonata.admin.controller.admin::retrieveAutocompleteItemsAction` also. The code should be changed to reflect that (by extracting the last part of the string).

**Comment by greg0ire** [comment]
After [some reading](http://symfony.com/doc/current/book/routing.html#controller-string-syntax) this notation is called the logical controller name. Could you make a PR supporting your use case ?

**Comment by magedan** [comment]
I guess so :) will try tomorrow.

**Comment by greg0ire** [comment]
Thanks a lot! Shouldn't be too hard :)

**Comment by Kertudex** [comment]
That's true, i didn't think about that.What about adding the 'retrieveAutocompleteItems' (the content of $currentAction) in the default configuration file to use sonata admin search by default in the autocomplete research? This is the default behaviour we would expect isn't it ?

**Comment by greg0ire** [comment]
Not sure how to do that / what you are talking about, but I'm listening :) Using admin search in autocomplete research could become the default for entities that we know are indexed, yeah.

**Comment by Kertudex** [comment]
It is just adding the correct action name in the defaultValue because ES should be used in the autocompleteResearch. The Unit Tests should be updated accordingly. 

``` php
 ->children()
       ->scalarNode('finder')->isRequired()->end()
       ->arrayNode('actions')
        ->defaultValue(array('list', 'retrieveAutocompleteItems'))
        ->prototype('scalar')
        ->info('array of actions where elasticsearch has to be enabled')
 ->end()
```

**Comment by greg0ire** [comment]
Oh ok, yeah, looks good. Can one of you do that ?

**Comment by Kertudex** [comment]
I'll propose a PR to fix the initial issue and configure the autocomplete action to use ES by default.

**Comment by greg0ire** [comment]
Thanks a lot!

**Comment by greg0ire** [comment]
BTW, could you rename `fullCurrentAction` to `logicalControllerName` ? Let's use the same terminology as Symfony.

**Comment by greg0ire** [comment]
ping @Kertudex

**Comment by chervaliery** [comment]
I propose a fix as discussed above
