### ISSUE TITLE
"doctrine_orm_callback" datagrid filter doesn't work

### ISSUE THREAD

**Issue by magedan** [sonata-project/SonataAdminSearchBundle#4]
I'm trying to add "doctrine_orm_callback" datagrid filter, pretty like the same it is described in the documentation:

``` php
// ...

class MyAdmin extends Admin
{
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('my_filter', 'doctrine_orm_callback', array(
                'callback' => function($queryBuilder, $alias, $field, $value) {
                    if (!$value) {
                        return;
                    }

                    // query modification here
                    // ...

                    return true;
                }
            ))
        ;
    }

    // other methods
    // ...
}
```

This leads to the following error:

> Notice: Undefined index: my_filter
> in vendor/sonata-project/admin-search-bundle/Guesser/FilterTypeGuesser.php at line 69

``` php
$options['field_name'] = $metadata->fieldMappings[$propertyName]['fieldName'];
```

It should have been expected this way, because filter name is not mapped (neither indexed nor mapped by the entity).

Should there be a special check for a filter type or maybe `isset($metadata->fieldMappings[$propertyName]['fieldName'])` call?

**Comment by greg0ire** [comment]
I think you are right, there should be an nicer error message.
Would like to contribute it ? To be honest, @clebeaupin and I are very busy at the moment…

**Comment by magedan** [comment]
I'm not sure what is the best way to resolve this.

Sonata\DoctrineORMAdminBundle\Builder\DatagridBuilder has following method:

``` php
    public function addFilter(DatagridInterface $datagrid, $type, FieldDescriptionInterface $fieldDescription, AdminInterface $admin)
    {
        if ($type == null) {
            $guessType = $this->guesser->guessType($admin->getClass(), $fieldDescription->getName(), $admin->getModelManager());

            $type = $guessType->getType();

            $fieldDescription->setType($type);

            // ...
        } else {
            $fieldDescription->setType($type);
        }
        // ...
    }
```

while Sonata\AdminSearchBundle\Builder\ElasticaDatagridBuilder just use guesser without condition:

``` php
    public function addFilter(DatagridInterface $datagrid, $type = null, FieldDescriptionInterface $fieldDescription, AdminInterface $admin)
    {
        // Try to wrap all types to search types
        $guessType = $this->guesser->guessType($admin->getClass(), $fieldDescription->getName(), $admin->getModelManager());
        $type = $guessType->getType();
        $fieldDescription->setType($type);

        // ...
    }
```

If you give me any suggestions how to resolve this issue in a "good" way I will try to fix it.

**Comment by greg0ire** [comment]
@clebeaupin : could you please advise when you have time ? I am not sure why the elastica builder logic differs from the orm one on this particular point.

**Comment by OskarStark** [comment]
ping @magedan

**Comment by magedan** [comment]
I was able to replace `doctrine_orm_callback` with `sonata_search_elastica_callback` and it resolved my problem.
Not sure if issue should be closed, but I terrible am sorry for not helping on this, because I don't work on that project anymore..

**Comment by greg0ire** [comment]
Don't feel sorry, you already helped a lot! Closing.
