### ISSUE TITLE
Fill datagrid in show view with data from ES

### ISSUE THREAD

**Issue by oliver-schulz** [sonata-project/SonataAdminSearchBundle#54]
Hello,

i'am developing a small app which stores some API configuration as normal doctrine entity.

In my example i have an API entity wich configures some API import stuff. When i import from this API the app stores the returning data into a separated ES index. 

Now i am trying to implement a show view for a API Entity which also shows the related ES Data. My current result is a Controller which overrides the CRUDController:show() and loads some data. 

My problem is now, how can i fill a AdminBundle Datagrid with Elastic Data without having some "real" entities in my SQL Database?

pseudo code:
```php
$results = $elasticsearchManager->execute(
            ['AppBundle:ApiDocument'],
            $search
        );
$datagrid = $this->admin->buildDataGrid($results);

return $this->render($this->admin->getTemplate('show'), array(
            'action' => 'show',
            'object' => $object,
            'elements' => $this->admin->getShow(),
            'datagrid' => $datagrid
        ), null);

```
Currently i am using the ongr/ElasticsearchBundle to communicate with my ES Cluster.

Any help or ideas welcome, thanks!

**Comment by greg0ire** [comment]
AFAIK is only for indexed entities/document, not sure it can work without… what you want is a persistence bundle… if you want to extend this bundle to make the backing optional, PRs are welcome I guess.

An obvious thing that misses is a model manager implementation : https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Model/ModelManagerInterface.php

Here are some : 
- https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/Model/ModelManager.php
- https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/1.x/Model/ModelManager.php

**Comment by oliver-schulz** [comment]
Thanks a lot for your help!
What i did so far:
1. i copied Sonata/DoctrineOrmAdminBundle and named it Sonata/ElastichsearchAdminBundle
2. Removed most Doctrine Related Stuff and replaced it with Ongr/ElasticsearchBundle stuff

Now i can make the Basic CRUD Stuff with Elasticsearch only Documents, also the Datagrid and Filters are working for now.

I will publish the code in the next view days, when i managed some configuration issues related to ES and the bundle.

**Comment by greg0ire** [comment]
Great job, congrats!

**Comment by OskarStark** [comment]
any news @oliver-schulz ?

**Comment by oliver-schulz** [comment]
I never finished my code, because i dropped the hole AdminBundle out of my project.

I still have the WIP Code, if this will help?

**Comment by jordisala1991** [comment]
Not sure how related is this issue, with this bundle, it looks more like a question for Stackoverflow.

Closing for now.
