### ISSUE TITLE
How to use CallbackFilter?

### ISSUE THREAD

**Issue by magedan** [sonata-project/SonataAdminSearchBundle#8]
I can see that filter set has Sonata\AdminSearchBundle\Filter\CallbackFilter but it seems it can't be used. It is not declared as a service (like, for example "sonata.admin.search.filter.type.string") and can't be recognized by Sonata\AdminSearchBundle\Guesser\FilterTypeGuesser.

**Comment by greg0ire** [comment]
I copied all the filters from the doctrine ORM bundle. Only a few of them have been adapted for ES. I think it simply is unusable for the moment, until someone decides to implement it.
